# Generated by Django 5.1.3 on 2024-11-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("face_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="music_settings",
            field=models.JSONField(default=list),
        ),
    ]
